import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav>
        <ul>
          <li>
            <Link href='/posts/first-post'>
              <a>My first post!</a>
            </Link>
          </li>
          <li>
            <Link href='#'>
              <a>Second</a>
            </Link>
          </li>
          <li>
            <Link href='#'>
              <a>Third</a>
            </Link>
          </li>
          <li>
            <Link href='#'>
              <a>Fourth</a>
            </Link>
          </li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
